#!/bin/bash

mkdir -p -m 755 /Applications/Firefox.app/Contents/MacOS/distribution/bundles/ 

ln -s /Library/Application\ Support/FirefoxCCK/underarmour-cck@extensions.underarmour.com /Applications/Firefox.app/Contents/MacOS/distribution/bundles/

exit 0