#!/bin/bash

# Creates a directory inside the Firefox bundle, and then symlinks the cck folder

mkdir -p -m 755 /Applications/Firefox.app/Contents/MacOS/distribution/bundles/ 

ln -s /Library/Application\ Support/CCK/underarmour-cck@extensions.underarmour.com /Applications/Firefox.app/Contents/MacOS/distribution/bundles/

exit 0